import { foodCategories } from "../lib/db";
import { mergeArrayAllFoodAndSelectedFood } from "./mergeSelectedAndOtherFoodUtils";

test("returns the correct merged array if called", () => {
  const result = mergeArrayAllFoodAndSelectedFood(
    foodCategories,
    selectedFoodCategories
  );
  expect(result).toEqual([
    {
      id: "1",
      name: "Vollkorngetreide",
      slug: "vollkorngetreide",
      recommendedConsumption: 232,
      recommendedExample:
        "2 Tassen Vollkornreis und 1,5 Scheiben Vollkornroggenbrot",
      maxRange: 464,
      maxRangeInputField: 600,
      consumedQuantity: 0,
    },
    {
      id: "2",
      name: "Stärkehaltiges Gemüse",
      slug: "staerkehaltiges-gemuese",
      recommendedConsumption: 50,
      recommendedExample: "1 kleine Kartoffel oder 2 kleine Maniokwurzeln",
      maxRange: 100,
      maxRangeInputField: 400,
      consumedQuantity: 0,
    },
    {
      id: "3",
      name: "Gemüse",
      slug: "gemuese",
      recommendedConsumption: 300,
      recommendedExample:
        "1 mittelgroße Karotte, 1 kleine Tomate, 1 kleine Zucchini",
      maxRange: 600,
      maxRangeInputField: 600,
      consumedQuantity: 0,
    },
    {
      id: "4",
      name: "Obst",
      slug: "obst",
      recommendedConsumption: 200,
      recommendedExample: "1 mittelgroßer Apfel und 1 mittelgroße Banane",
      maxRange: 300,
      maxRangeInputField: 600,
      consumedQuantity: 0,
    },
    {
      id: "5",
      name: "Rind, Lamm o. Schwein",
      slug: "fleisch",
      recommendedConsumption: 14,
      recommendedExample: "1 Scheibe mageres Rindfleisch",
      maxRange: 28,
      maxRangeInputField: 300,
      consumedQuantity: 50,
    },
    {
      id: "6",
      name: "Geflügel",
      slug: "gefluegel",
      recommendedConsumption: 29,
      recommendedExample: "1/2 Hühnerbrust",
      maxRange: 58,
      maxRangeInputField: 300,
      consumedQuantity: 100,
    },

    {
      id: "7",
      name: "Eier",
      slug: "eier",
      recommendedConsumption: 13,
      recommendedExample: "1 kleines Ei",
      maxRange: 25,
      maxRangeInputField: 100,
      consumedQuantity: 13,
    },
    {
      id: "8",
      name: "Fisch",
      slug: "fisch",
      recommendedConsumption: 28,
      recommendedExample: "1 Scheibe Lachs oder Thunfisch",
      maxRange: 100,
      maxRangeInputField: 300,
      consumedQuantity: 0,
    },
    {
      id: "9",
      name: "Hülsenfrüchte",
      slug: "huelsenfruechte",
      recommendedConsumption: 75,
      recommendedExample: "1/2 Tasse gekochte Bohnen oder Kichererbsen",
      maxRange: 100,
      maxRangeInputField: 200,
      consumedQuantity: 0,
    },
    {
      id: "10",
      name: "Nüsse",
      slug: "nuesse",
      recommendedConsumption: 50,
      recommendedExample: "1/4 Tasse Nüsse",
      maxRange: 75,
      maxRangeInputField: 200,
      consumedQuantity: 0,
    },
    {
      id: "11",
      name: "Milchprodukte",
      slug: "milchprodukte",
      recommendedConsumption: 250,
      recommendedExample:
        "1 Tasse fettarme Milch oder 1 kleines Stück fettarmer Käse",
      maxRange: 500,
      maxRangeInputField: 600,
      consumedQuantity: 0,
    },
    {
      id: "12",
      name: "Ungesättigte Fette",
      slug: "ungesaettigte-fette",
      recommendedConsumption: 40,
      recommendedExample: "knapp 3 Esslöffel Olivenöl",
      maxRange: 80,
      maxRangeInputField: 200,
      consumedQuantity: 0,
    },
    {
      id: "13",
      name: "Gesättigte Fette",
      slug: "gesaettigte-fette",
      recommendedConsumption: 11.8,
      recommendedExample: "2 TL Kokosöl oder 1,5 TL Butter",
      maxRange: 11.8,
      maxRangeInputField: 200,
      consumedQuantity: 0,
    },
    {
      id: "14",
      name: "Süßungsmittel",
      slug: "suessungsmittel",
      recommendedConsumption: 31,
      recommendedExample: "2 EL Honig",
      maxRange: 31,
      maxRangeInputField: 200,
      consumedQuantity: 0,
    },
  ]);
});

const selectedFoodCategories = [
  {
    id: "5",
    name: "Rind, Lamm o. Schwein",
    slug: "fleisch",
    recommendedConsumption: 14,
    recommendedExample: "1 Scheibe mageres Rindfleisch",
    maxRange: 28,
    maxRangeInputField: 300,
    consumedQuantity: 50,
  },
  {
    id: "6",
    name: "Geflügel",
    slug: "gefluegel",
    recommendedConsumption: 29,
    recommendedExample: "1/2 Hühnerbrust",
    maxRange: 58,
    maxRangeInputField: 300,
    consumedQuantity: 100,
  },

  {
    id: "7",
    name: "Eier",
    slug: "eier",
    recommendedConsumption: 13,
    recommendedExample: "1 kleines Ei",
    maxRange: 25,
    maxRangeInputField: 100,
    consumedQuantity: 13,
  },
];
